- name: Update alle LXC's system
  hosts: all
  tasks:
    - name: apt update & apt upgrade
      block: 
        - name: Update and upgrade
          apt:
            update_cache: true
            cache_valid_time: 3600
            upgrade: dist

        - name: Check if reboot required
          stat:
            path: /var/run/reboot-required
          register: reboot_required_file

        - name: Reboot if required
          reboot:
          when: reboot_required_file.stat.exists == true
      become: true